-- SMIHD-5304 - add PO Notify Date to SMI and AFCO Reporting feeds
-- script to add tblPOMaster.ixNotifyDate

-- USE [AFCOReporting]
USE [SMI Reporting]

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.tblPOMaster ADD
	ixNotifyDate smallint NULL,
	dtDateLastSOPUpdate datetime NULL,
	ixTimeLastSOPUpdate int NULL
GO
--ROLLBACK TRAN
COMMIT
