BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.tblSKU ADD
	ixProposer varchar(10) NULL,
	ixAnalyst varchar(10) NULL,
	ixMerchant varchar(10) NULL,
	ixBuyer varchar(10) NULL
GO
ALTER TABLE dbo.tblSKU SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
