-- SMIHD-11280 - add flgProp65 to tblSKU

-- apply to BOTH SMIReporting AND AFCOReporting
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.tblSKU ADD
	flgProp65 tinyint NULL
GO
ALTER TABLE dbo.tblSKU SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
