--CREATE CLUSTERED INDEX _dta_index_tblBin_c_7_1883153754__K1_K2 ON [tblBin] ([ixBin], [ixLocation])
--CREATE CLUSTERED INDEX _dta_index_tblBinSku_c_7_1899153811__K3_K2_K1 ON [tblBinSku] ([ixBin], [sCID], [ixSKU])
--CREATE INDEX _dta_index_tblBinSku_7_2069582411__K8_K3 ON [tblBinSku] ([sPickingBin], [ixSKU])
--CREATE INDEX _dta_index_tblBinSku_7_1899153811__K1 ON [tblBinSku] ([ixBin])
--CREATE INDEX IX_tblBinSku_ixBin_ixLocation ON [tblBinSku] ([ixBin], [ixLocation])
--CREATE INDEX _dta_index_tblBOMTemplateDetail_7_2094630505__K2 ON [tblBOMTemplateDetail] ([ixSKU])
--CREATE INDEX _dta_index_tblBOMTransferDetail_7_507148852__K2_K1_3 ON [tblBOMTransferDetail] ([ixSKU], [ixTransferNumber]) INCLUDE ([iQuantity])
--CREATE INDEX _dta_index_tblBOMTransferDetail_7_507148852__K1_K2_3 ON [tblBOMTransferDetail] ([ixTransferNumber], [ixSKU]) INCLUDE ([iQuantity])
--CREATE CLUSTERED INDEX _dta_index_tblBOMTransferMaster_c_7_135671531__K1 ON [tblBOMTransferMaster] ([ixTransferNumber])
--CREATE INDEX _dta_index_tblBOMTransferMaster_7_135671531__K1_6 ON [tblBOMTransferMaster] ([ixTransferNumber]) INCLUDE ([ixCreateDate])
--CREATE INDEX IX_tblBOMTransferMaster_flgReverseBOM_dtCanceledDate ON [tblBOMTransferMaster] ([flgReverseBOM], [dtCanceledDate])
--CREATE INDEX IX_tblCatalogDetail_ixSKU ON [tblCatalogDetail] ([ixSKU])
--CREATE INDEX IX_tblCatalogDetail_ixCatalog_ixSKU ON [tblCatalogDetail] ([ixCatalog], [ixSKU])

--CREATE INDEX _dta_index_tblCreditMemoDetail_7_423672557__K2_K3_5_6_7 ON [tblCreditMemoDetail] ([ixCreditMemo], [ixSKU]) INCLUDE ([iQuantityCredited], [mUnitPrice], [mUnitCost])
--CREATE INDEX _dta_index_tblCreditMemoMaster_7_117575457__K10_K8_K1 ON [tblCreditMemoMaster] ([ixOrderTaker], [dtCreateDate], [ixCreditMemo])
--CREATE INDEX _dta_index_tblCreditMemoMaster_7_117575457__K8_K10_K1 ON [tblCreditMemoMaster] ([dtCreateDate], [ixOrderTaker], [ixCreditMemo])
--CREATE INDEX _dta_index_tblCreditMemoMaster_7_117575457__K8_K10_K4_K1 ON [tblCreditMemoMaster] ([dtCreateDate], [ixOrderTaker], [ixCreateDate], [ixCreditMemo])
CREATE INDEX IX_tblCreditMemoMaster_ixCreditMemo ON [tblCreditMemoMaster] ([ixCreditMemo])
CREATE CLUSTERED INDEX _dta_index_tblCustomer_c_7_213575799__K1 ON [tblCustomer] ([ixCustomer])
CREATE INDEX _dta_index_tblCustomer_7_213575799__K1_K2 ON [tblCustomer] ([ixCustomer], [sCustomerType])
CREATE INDEX _dta_index_tblCustomer_7_213575799__K1 ON [tblCustomer] ([ixCustomer])
CREATE CLUSTERED INDEX _dta_index_tblCustomerOffer_c_7_2089058478__K1 ON [tblCustomerOffer] ([ixCustomerOffer])
CREATE INDEX _dta_index_tblDate_7_2073058421__K2_K1 ON [tblDate] ([dtDate], [ixDate])
CREATE INDEX _dta_index_tblDate_7_2073058421__K2_K1_3_4_5_6_7_8_9 ON [tblDate] ([dtDate], [ixDate]) INCLUDE ([iQuarter], [iPeriod], [iISOWeek], [iDayOfWeek], [iDayOfYear], [iYear], [iPeriodYear])
CREATE INDEX _dta_index_tblDate_7_203147769__K2_1 ON [tblDate] ([dtDate]) INCLUDE ([ixDate])
CREATE INDEX _dta_index_tblDate_7_203147769__K1_K2 ON [tblDate] ([ixDate], [dtDate])
CREATE INDEX _dta_index_tblDate_7_203147769__K1_2 ON [tblDate] ([ixDate]) INCLUDE ([dtDate])
CREATE INDEX _dta_index_tblDate_7_203147769__K9_K4_K1 ON [tblDate] ([iPeriodYear], [iPeriod], [ixDate])
CREATE INDEX _dta_index_tblDate_7_203147769__K4 ON [tblDate] ([iPeriod])
CREATE INDEX _dta_index_tblDate_7_203147769__K4_K9 ON [tblDate] ([iPeriod], [iPeriodYear])
CREATE INDEX _dta_index_tblDate_7_203147769__K9_K2_K1_K4 ON [tblDate] ([iPeriodYear], [dtDate], [ixDate], [iPeriod])
CREATE INDEX IX_tblDate_iISOWeek_iDayOfWeek_iYear ON [tblDate] ([iISOWeek], [iDayOfWeek], [iYear]) INCLUDE ([dtDate])
CREATE INDEX _dta_index_tblDate_7_203147769__K1 ON [tblDate] ([ixDate])
CREATE CLUSTERED INDEX _dta_index_tblDropship_c_7_375672386__K5_K2 ON [tblDropship] ([ixSpecialOrder], [ixSKU])



CREATE INDEX _dta_index_tblEmployee_7_2071678428__K1_K3_2 ON [tblEmployee] ([ixEmployee], [sFirstname]) INCLUDE ([sLastname])
CREATE INDEX _dta_index_tblInventoryForecast_7_2118298606__K1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19 ON [tblInventoryForecast] ([ixSKU]) INCLUDE ([iLostSales], [iQuantityCommitted], [i12MonthSales], [iNeg3MonthSales], [iNeg2MonthSales], [iNeg1MonthSales], [iMTDSales], [iThisMonthForecast], [iPlus1MonthSales], [iPlus2MonthSales], [iPlus3MonthSales], [iRestockQuantity], [dLeadTime], [i2MonthSupply], [i4MonthSupply], [i6MonthSupply], [i12MonthSupply], [iReorderPoint])
CREATE INDEX IX_tblInventoryReceipt_ixInventoryReceipt ON [tblInventoryReceipt] ([ixInventoryReceipt])
CREATE INDEX IX_tblInventoryReceipt_ixSKU ON [tblInventoryReceipt] ([ixSKU])
CREATE CLUSTERED INDEX _dta_index_tblJobClock_c_7_382624406__K1_K6_K5_K4 ON [tblJobClock] ([ixDate], [sJob], [ixEmployee], [dtDate])
CREATE INDEX _dta_index_tblJobClock_7_2121058592__K2_K5_K6_K7_3_4 ON [tblJobClock] ([ixDate], [sJob], [ixEmployee], [dtDate]) INCLUDE ([iStartTime], [iStopTime])
CREATE INDEX _dta_index_tblJobClock_7_2121058592__K2_K7_K6_K5 ON [tblJobClock] ([ixDate], [dtDate], [ixEmployee], [sJob])
CREATE INDEX _dta_index_tblKit_7_606625204__K7_1_2 ON [tblKit] ([ixChangeDate]) INCLUDE ([ixKitSKU], [ixSKU])
CREATE CLUSTERED INDEX _dta_index_tblOrder_c_7_1989582126__K1_K3 ON [tblOrder] ([ixOrder], [ixOrderDate])
CREATE INDEX IX_tblOrder_sOptimalShipOrigination_dtShippedDate ON [tblOrder] ([sOptimalShipOrigination], [dtShippedDate]) INCLUDE ([ixOrder], [ixOrderDate], [sShipToZip])
CREATE INDEX _dta_index_tblOrder_7_133575514__K21_1 ON [tblOrder] ([sOrderStatus]) INCLUDE ([ixOrder])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K24_K1_K21_K7_17 ON [tblOrder] ([dtOrderDate], [ixOrder], [sOrderStatus], [sOrderType]) INCLUDE ([mMerchandise])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K3_K21_K17_K1 ON [tblOrder] ([ixOrderDate], [sOrderStatus], [mMerchandise], [ixOrder])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K21_K8_K2_K1 ON [tblOrder] ([sOrderStatus], [sOrderChannel], [ixCustomer], [ixOrder])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K13_K1_K3_K7 ON [tblOrder] ([sMatchbackSourceCode], [ixOrder], [ixOrderDate], [sOrderType])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K21_K3 ON [tblOrder] ([sOrderStatus], [ixOrderDate])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K11_K24_1_31 ON [tblOrder] ([iShipMethod], [dtOrderDate]) INCLUDE ([ixOrder], [mPublishedShipping])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K11_K6_1_2_3_4_5_7_8_9_10_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31 ON [tblOrder] ([iShipMethod], [sShipToZip]) INCLUDE ([ixOrder], [ixCustomer], [ixOrderDate], [sShipToCity], [sShipToState], [sOrderType], [sOrderChannel], [sShipToCountry], [ixShippedDate], [sSourceCodeGiven], [sMatchbackSourceCode], [sMethodOfPayment], [sOrderTaker], [sPromoApplied], [mMerchandise], [mShipping], [mTax], [mCredits], [sOrderStatus], [flgIsBackorder], [mMerchandiseCost], [dtOrderDate], [dtShippedDate], [ixAccountManager], [ixOrderTime], [mPromoDiscount], [ixAuthorizationStatus], [ixOrderType], [mPublishedShipping])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K8_K1_K24 ON [tblOrder] ([sOrderChannel], [ixOrder], [dtOrderDate])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K5_K24_K1_K3_17 ON [tblOrder] ([sShipToState], [dtOrderDate], [ixOrder], [ixOrderDate]) INCLUDE ([mMerchandise])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K21_K25_K1_K3_K2_K13_K7_17_23 ON [tblOrder] ([sOrderStatus], [dtShippedDate], [ixOrder], [ixOrderDate], [ixCustomer], [sMatchbackSourceCode], [sOrderType]) INCLUDE ([mMerchandise], [mMerchandiseCost])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K2_K1_K17_K23_K25_K21_K8_K12_K7 ON [tblOrder] ([ixCustomer], [ixOrder], [mMerchandise], [mMerchandiseCost], [dtShippedDate], [sOrderStatus], [sOrderChannel], [sSourceCodeGiven], [sOrderType])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K7_K21_K1 ON [tblOrder] ([sOrderType], [sOrderStatus], [ixOrder])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K3_K1_K21_K8_K2_17_22 ON [tblOrder] ([ixOrderDate], [ixOrder], [sOrderStatus], [sOrderChannel], [ixCustomer]) INCLUDE ([mMerchandise], [flgIsBackorder])




CREATE INDEX _dta_index_tblOrder_7_1989582126__K21_K25_K3_K1_8_11_17_22 ON [tblOrder] ([sOrderStatus], [dtShippedDate], [ixOrderDate], [ixOrder]) INCLUDE ([sOrderChannel], [iShipMethod], [mMerchandise], [flgIsBackorder])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K2_K24_K21_K17 ON [tblOrder] ([ixCustomer], [dtOrderDate], [sOrderStatus], [mMerchandise])
CREATE INDEX _dta_index_tblOrder_7_1989582126__K16_K24_K2_K17_K21_K1_23_28 ON [tblOrder] ([sPromoApplied], [dtOrderDate], [ixCustomer], [mMerchandise], [sOrderStatus], [ixOrder]) INCLUDE ([mMerchandiseCost], [mPromoDiscount])
CREATE INDEX _dta_index_tblOrder_7_335340259__K24 ON [tblOrder] ([dtOrderDate])
CREATE CLUSTERED INDEX _dta_index_tblOrderLine_c_7_1077578877__K11_K9 ON [tblOrderLine] ([flgLineStatus], [dtShippedDate])
CREATE INDEX IX_tblOrderLine_ixOrder ON [tblOrderLine] ([ixOrder]) INCLUDE ([ixPrintedDate], [ixPrintedTime])
CREATE INDEX IX_tblOrderLine_ixSKU_flgLineStatus_flgKitComponent_dtOrderDate ON [tblOrderLine] ([ixSKU], [flgLineStatus], [flgKitComponent], [dtOrderDate]) INCLUDE ([mCost], [iOrdinality], [iKitOrdinality])
CREATE INDEX _dta_index_tblOrderLine_7_21575115__K1_2_3_4_5_6_7_8_9 ON [tblOrderLine] ([ixOrder]) INCLUDE ([ixCustomer], [ixSKU], [ixShippedDate], [ixOrderDate], [iQuantity], [mUnitPrice], [mExtendedPrice], [flgLineStatus])
CREATE INDEX _dta_index_tblOrderLine_7_1077578877__K9_K1_K3_6_8_13 ON [tblOrderLine] ([flgLineStatus], [ixOrder], [ixSKU]) INCLUDE ([iQuantity], [mExtendedPrice], [mExtendedCost])
CREATE INDEX _dta_index_tblOrderLine_7_1077578877__K1_K3_6_8 ON [tblOrderLine] ([ixOrder], [ixSKU]) INCLUDE ([iQuantity], [mExtendedPrice])
CREATE INDEX _dta_index_tblOrderLine_7_1077578877__K3_8 ON [tblOrderLine] ([ixSKU]) INCLUDE ([mExtendedPrice])
CREATE INDEX _dta_index_tblOrderLine_7_1077578877__K15_K1 ON [tblOrderLine] ([iOrdinality], [ixOrder])
CREATE INDEX _dta_index_tblOrderLine_7_1077578877__K1_K11_K9_13 ON [tblOrderLine] ([ixOrder], [dtShippedDate], [flgLineStatus]) INCLUDE ([mExtendedCost])
CREATE INDEX _dta_index_tblOrderLine_7_1077578877__K14_K1_8_9_11_13 ON [tblOrderLine] ([flgKitComponent], [ixOrder]) INCLUDE ([mExtendedPrice], [flgLineStatus], [dtShippedDate], [mExtendedCost])
CREATE INDEX _dta_index_tblOrderLine_7_1077578877__K14_K1_9_11_13 ON [tblOrderLine] ([flgKitComponent], [ixOrder]) INCLUDE ([flgLineStatus], [dtShippedDate], [mExtendedCost])
CREATE INDEX _dta_index_tblOrderLine_7_1077578877__K9_K14_K10_K3_6_13 ON [tblOrderLine] ([flgLineStatus], [flgKitComponent], [dtOrderDate], [ixSKU]) INCLUDE ([iQuantity], [mExtendedCost])
CREATE INDEX _dta_index_tblOrderLine_7_1077578877__K1_K9_K3_6_13 ON [tblOrderLine] ([ixOrder], [flgLineStatus], [ixSKU]) INCLUDE ([iQuantity], [mExtendedCost])
CREATE INDEX _dta_index_tblOrderLine_7_1077578877__K9_K10_K14_K1_K3_6_7_12 ON [tblOrderLine] ([flgLineStatus], [dtOrderDate], [flgKitComponent], [ixOrder], [ixSKU]) INCLUDE ([iQuantity], [mUnitPrice], [mCost])
CREATE INDEX _dta_index_tblOrderLine_7_1077578877__K3_K1_K2_K9_K10 ON [tblOrderLine] ([ixSKU], [ixOrder], [ixCustomer], [flgLineStatus], [dtOrderDate])
CREATE INDEX _dta_index_tblOrderLine_7_1077578877__K10_K9_K11_K3_K14_K7_K1_6 ON [tblOrderLine] ([dtOrderDate], [flgLineStatus], [dtShippedDate], [ixSKU], [flgKitComponent], [mUnitPrice], [ixOrder]) INCLUDE ([iQuantity])
CREATE CLUSTERED INDEX _dta_index_tblOrderRouting_c_7_110623437__K1 ON [tblOrderRouting] ([ixOrder])
CREATE CLUSTERED INDEX _dta_index_tblPackage_c_7_158623608__K2_K1 ON [tblPackage] ([sTrackingNumber], [ixOrder])
CREATE CLUSTERED INDEX _dta_index_tblPODetail_c_7_830626002__K2 ON [tblPODetail] ([ixSKU])
CREATE INDEX _dta_index_tblPODetail_7_830626002__K1_K9_K3_K2 ON [tblPODetail] ([ixPO], [iQuantityPosted], [iQuantity], [ixSKU])
CREATE INDEX _dta_index_tblPODetail_7_1126295072__K1_K2_K7_3_8_9 ON [tblPODetail] ([ixPO], [ixSKU], [ixExpectedDeliveryDate]) INCLUDE ([iQuantity], [iQuantityReceivedPending], [iQuantityPosted])
CREATE INDEX _dta_index_tblPOMaster_7_958626458__K28_K29_K1 ON [tblPOMaster] ([flgIssued], [flgOpen], [ixPO])
CREATE INDEX IX_tblReceiver_ixReceiver ON [tblReceiver] ([ixReceiver])
CREATE INDEX IX_tblReceivingWorksheet_ixReceivingWorksheet ON [tblReceivingWorksheet] ([ixReceivingWorksheet])
CREATE CLUSTERED INDEX _dta_index_tblSKU_c_7_1326627769__K1 ON [tblSKU] ([ixSKU])
CREATE INDEX _dta_index_tblSKU_7_85575343__K9_1 ON [tblSKU] ([ixPGC]) INCLUDE ([ixSKU])
CREATE INDEX _dta_index_tblSKU_7_85575343__K1_K10_K9 ON [tblSKU] ([ixSKU], [sDescription], [ixPGC])
CREATE INDEX _dta_index_tblSKU_7_85575343__K1 ON [tblSKU] ([ixSKU])
CREATE INDEX _dta_index_tblSKU_7_1938105945__K15_K14_K1_2_8_9_10 ON [tblSKU] ([ixCreateDate], [iQOS], [ixSKU]) INCLUDE ([mPriceLevel1], [mAverageCost], [ixPGC], [sDescription])
CREATE INDEX _dta_index_tblSKU_7_1326627769__K1_K10_K16_K19_K22_K20_K24_K36_K28_K35_K12_K11_K34_K31_K38_K29_2_3_4_5_6_7_8_9_15_17_18_21_23_ ON [tblSKU] ([ixSKU], [sDescription], [dtCreateDate], [dtDiscontinuedDate], [dWeight], [flgActive], [flgAdditionalHandling], [flgIntangible], [flgIsKit], [flgShipAloneStatus], [flgTaxable], [flgUnitOfMeasure], [iCartonQuantity], [iHeight], [iLeadTime], [iLength]) INCLUDE ([mPriceLevel1], [mPriceLevel2], [mPriceLevel3], [mPriceLevel4], [mPriceLevel5], [mLatestCost], [mAverageCost], [ixPGC], [ixCreateDate], [ixRoyaltyVendor], [ixDiscontinuedDate], [sBaseIndex], [sOriginalSource], [ixBrand], [ixOriginalPart], [ixHarmonizedTariffCode], [iWidth], [iMaxQOS], [iRestockPoint], [ixCreator])
CREATE INDEX _dta_index_tblSKU_7_1326627769__K1_2_7_10_13 ON [tblSKU] ([ixSKU]) INCLUDE ([mPriceLevel1], [mLatestCost], [sDescription], [iQAV])
CREATE INDEX _dta_index_tblSKU_7_1326627769__K1_2_9_10_11_14_15_24_25 ON [tblSKU] ([ixSKU]) INCLUDE ([mPriceLevel1], [ixPGC], [sDescription], [flgUnitOfMeasure], [iQOS], [ixCreateDate], [flgAdditionalHandling], [ixBrand])
CREATE INDEX _dta_index_tblSKU_7_1326627769__K20_1 ON [tblSKU] ([flgActive]) INCLUDE ([ixSKU])
CREATE INDEX _dta_index_tblSKU_7_1326627769__K1_K9_K10_K29_K30_K31_K22_K35_K32_K34 ON [tblSKU] ([ixSKU], [ixPGC], [sDescription], [iLength], [iWidth], [iHeight], [dWeight], [flgShipAloneStatus], [iMaxQOS], [iCartonQuantity])
CREATE INDEX _dta_index_tblSKU_7_1326627769__K28_K1_K10 ON [tblSKU] ([flgIsKit], [ixSKU], [sDescription])
CREATE INDEX _dta_index_tblSKU_7_1326627769__K1_K21 ON [tblSKU] ([ixSKU], [sBaseIndex])
CREATE INDEX _dta_index_tblSKU_7_1326627769__K36_K13_K9_K1 ON [tblSKU] ([flgIntangible], [iQAV], [ixPGC], [ixSKU])
CREATE INDEX _dta_index_tblSKUIndex_7_973246522__K1 ON [tblSKUIndex] ([ixBaseSKU])
CREATE INDEX IX_tblSKULocation_ixLocation ON [tblSKULocation] ([ixLocation]) INCLUDE ([ixSKU])
CREATE INDEX _dta_index_tblSKULocation_7_934294388__K1_3_4_6 ON [tblSKULocation] ([ixSKU]) INCLUDE ([iQOS], [iQAV], [iQCB])
CREATE CLUSTERED INDEX _dta_index_tblSKUTransaction_c_7_1694629080__K1_K4 ON [tblSKUTransaction] ([ixDate], [iSeq])
CREATE INDEX _dta_index_tblSnapAdjustedMonthlySKUSales_7_1012198656__K1_K2_3_4_5_6 ON [tblSnapAdjustedMonthlySKUSales] ([iYearMonth], [ixSKU]) INCLUDE ([AdjustedSales], [AdjustedQTYSold], [AdjustedGP], [AVGInvCost])
CREATE INDEX _dta_index_tblSnapAdjustedMonthlySKUSales_7_1012198656__K1_K2_3_4_5 ON [tblSnapAdjustedMonthlySKUSales] ([iYearMonth], [ixSKU]) INCLUDE ([AdjustedSales], [AdjustedQTYSold], [AdjustedGP])
CREATE CLUSTERED INDEX _dta_index_tblSnapshotSKU_c_7_1947153982__K5_K1 ON [tblSnapshotSKU] ([ixSKU], [ixDate])
CREATE INDEX _dta_index_tblSnapshotSKU_7_1947153982__K1_K5_3 ON [tblSnapshotSKU] ([ixSKU], [ixDate]) INCLUDE ([mFIFOExtendedCost])
CREATE INDEX _dta_index_tblSourceCode_7_2105058535__K4_K1 ON [tblSourceCode] ([ixCatalog], [ixSourceCode])
CREATE INDEX _dta_index_tblSourceCode_7_1213247377__K1_K4_K10_K9_K5 ON [tblSourceCode] ([ixSourceCode], [ixCatalog], [ixMostSimilarSourceCode], [iQuantityPrinted], [sDescription])
CREATE INDEX IX_tblTime_ixTime ON [tblTime] ([ixTime]) INCLUDE ([chTime])
CREATE INDEX IX_tblTimeClock_ixDate_ixEmployee ON [tblTimeClock] ([ixDate], [ixEmployee])
CREATE INDEX IX_tblTrailerZipTNT_ixZipCode ON [tblTrailerZipTNT] ([ixZipCode])
CREATE INDEX _dta_index_tblVendor_7_5575058__K1_2 ON [tblVendor] ([ixVendor]) INCLUDE ([sName])
-- 
CREATE INDEX _dta_index_tblVendor_7_694293533__K1_2_18 ON [tblVendor] ([ixVendor]) INCLUDE ([sName], [ixBuyer])
CREATE CLUSTERED INDEX _dta_index_tblVendorSKU_c_7_725577623__K3_K6 ON [tblVendorSKU] ([ixSKU], [iOrdinality])
CREATE INDEX _dta_index_tblVendorSKU_7_725577623__K4_K6_K3_2_5 ON [tblVendorSKU] ([ixVendor], [iOrdinality], [ixSKU]) INCLUDE ([sVendorSKU], [mCost])
-- 
CREATE INDEX _dta_index_tblVendorSKU_7_725577623__K6_K4_2_3_5 ON [tblVendorSKU] ([iOrdinality], [ixVendor]) INCLUDE ([sVendorSKU], [ixSKU], [mCost])
CREATE INDEX _dta_index_tblVendorSKU_7_725577623__K4_3_5_6 ON [tblVendorSKU] ([ixVendor]) INCLUDE ([ixSKU], [mCost], [iOrdinality])