-- DELETE records older than 2 years from tblFIFODetail

SELECT MIN(ixDate) FROM tblFIFODetail -- 17899

select count(*) 
from tblFIFODetail      -- 312,707,828 
where ixDate <= 17898   --  87,043,247 to be DELETED

select * from tblDate where ixDate = 17899 -- 01/01/2017
/*
18264	01/01/2018
17899	01/01/2017
*/


/* TABLE STATS
    -- right click table properties>Storage

        Data    Index   Total
            space   space   space
Date        (GB)    (GB)    (GB)    Records
====        ======  =====   =====   ===========
12/31/18     8.6     4.2    12.8    179,647,557
12/28/18    14.6     7.3    21.9    312,707,828 

*/

SELECT * -- OPEN TRANSACTIONS
FROM sys.sysprocesses 
WHERE open_tran = 1
    and program_name <> 'Replication Distribution Agent' 
    
/*                                     
ROWCOUNT    mins    sets x rec  rec/min
========    ====    ========    =======
  1m        13.5    10x1m        740k
  1m        31      27x1m        870k
  2m        2.3      1x2m        917k
  2m        2.3      6x2m       1.02m

*/
-- SET ROWCOUNT 2000000
-- SET ROWCOUNT 1000000 -- start at 1m  as of 12/30/18 SQL can delete approx 1m rec/minute.  THIS TABLE IS NOT REPLICATED TO AWS so it's safe to delete large batches at a time
-- SET ROWCOUNT 230499

SET ROWCOUNT 1000000 -- start at 20k batches. add 20k for every minute the batch takes e.g. 10 mins 200k
GO 
SELECT @@SPID as 'Current SPID' -- 110
GO                                                             

-- RECORDS LEFT TO ARCHIVE
SELECT count(*) 'REC to DEL' , CONVERT(VARCHAR,GETDATE(),22) 'As Of' 
FROM tblFIFODetail                                                           
WHERE ixDate <= 17898 
/*
    rec to DEL      mins    AsOf                                                        
    ==========      ====    =====================
    72,404,964      15      04/27/17  10:40 AM
    53,013,964	    ??      05/17/17  9:50:35 AM
    15,123,964	    13      06/07/17  9:08:06 AM
     5,000,000	    14      06/12/17  7:34:47 AM
     2,000,210      2.5     08
     
*/

SELECT CONVERT(VARCHAR,GETDATE(),22) 'START@' 
GO                                                                                                                    
                          DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 1'   
GO                                                   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 2'                                 
GO
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 3'
GO
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 4'
GO
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 5' 
GO
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 6'
GO
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 7'
GO
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 8'
GO
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 9'
GO
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 10'

-- sets 11-20
WAITFOR DELAY '00:00:01'; -- HH:MM:SS 
                          DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 11' 
GO                          
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 12'                                  
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 13'    
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 14'  
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 15' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 16'     
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 17' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 18' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 19' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 20'

-- sets 21-30
WAITFOR DELAY '00:00:01';  -- HH:MM:SS
                          DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 21' 
GO                             
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 22'                                  
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 23'    
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 24'  
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 25' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 26'     
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 27' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 28' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 29' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 30'
-- sets 31-40
WAITFOR DELAY '00:00:01';  -- HH:MM:SS
                          DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 31'
GO                             
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 32'                                 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 33'   
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 34' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 35'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 36'    
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 37'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 38'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 39'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 40'
-- sets 41-50
WAITFOR DELAY '00:05:10';  -- HH:MM:SS
                          DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 41'
GO                             
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 42'                                 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 43'   
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 44' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 45'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 46'    
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 57'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 48'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 49'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 50'
-- sets 51-60
WAITFOR DELAY '00:00:01';  -- HH:MM:SS
                          DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 51'
GO                             
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 52'                                 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 53'   
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 54' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 55'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 56'    
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 57'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 58'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 59'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 60'
-- sets 61-70
WAITFOR DELAY '00:00:01';  -- HH:MM:SS
                          DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 61'
GO                             
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 62'                                 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 63'   
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 64' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 65'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 66'    
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 67'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 68'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 69'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 70'
-- sets 71-80
WAITFOR DELAY '00:00:01';  -- HH:MM:SS
                          DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 71'
GO                             
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 72'  
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 73'   
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 74' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 75'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 76'    
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 77'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 78'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 79'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 80'
-- sets 81-90
WAITFOR DELAY '00:00:01';  -- HH:MM:SS
                          DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 81'
GO                             
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 82'  
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 83'   
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 84' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 85'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 86'    
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 87'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 88'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 89'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 90'
-- sets 91-100
WAITFOR DELAY '00:00:01';  -- HH:MM:SS
                          DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 91'
GO                             
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 92'  
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 93'   
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 94' 
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 95'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 96'    
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 97'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 98'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 99'
GO   
WAITFOR DELAY '00:00:01'; DELETE FROM [SMI Reporting].dbo.tblFIFODetail WITH(READPAST) WHERE ixDate <= 17898; SELECT CONVERT(VARCHAR,GETDATE(),22) 'END SET 100 - FINISHED BIATCH!!!!'
GO








set nocount off
/* You can change the batch size */
Declare @BatchSize int
set @BatchSize = 1

Declare @TestMode bit;
set @TestMode = 1 ; --When set to one it will rollback the transaction and only do one pass.

Declare @Date bigint -- This is the internal Pick Date number
set @Date =  17284 --	2015-04-27 

Declare @Count int
set @Count = 1
while exists( select top 1 1 from tblFIFODetail where ixDate <= @Date )
begin
       begin transaction
       -- SELECT  
       DELETE
       TOP (@BatchSize)
       -- *
       FROM tblFIFODetail 
       where ixDate <= @Date
              
       if @TestMode = 1
       begin
              rollback transaction
              set @Date = 0 -- For testing this gets us out of the loop
       end else
       begin
              COMMIT transaction
       end

       print cast(@Count * @BatchSize as nvarchar(max)) + ' Records Deleted'
       set @Count = @Count + 1
end
